### ISSUE TITLE
#TK43 Poder crear un anuncio de subasta

### ISSUE THREAD

**Issue by AhumadaCeleste** [rpgrca/proyecto-ispc-fullstack#108]

**Comment by rpgrca** [comment]
Te lo renombré, hacemos que sea para crear lotes, que tenga que ingresar una foto, un título, una descripción y un precio base para el producto, también ponerle el nombre de un consignatario.

**Comment by rpgrca** [comment]
La renombré, vamos a simplificar, que únicamente pueda crear un anuncio de una subasta, o sea que la página principal solo va a tener información de la próxima subasta. Así que tendría que subir una imagen, un texto y una fecha.
