### ISSUE TITLE
#TK04 Diseñar la pantalla de login en papel y lápiz

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#11]

**Comment by rpgrca** [comment]
Diseñar la pantalla de login con dos textboxes, uno para ingresar el correo electrónico, otro para ingresar la contraseña, y un botón para ejecutar el login. Además debe tener un link que diga "Olvidó password?".

**Comment by AhumadaCeleste** [comment]
![Logueo_nuevo_usuario](https://user-images.githubusercontent.com/106411071/192067947-069f6eff-d3de-401b-a4ae-d8cec2e549d3.jpg)

**Comment by AhumadaCeleste** [comment]
<img width="420" alt="Logueo_nuevo_usuario" src="https://user-images.githubusercontent.com/106411071/192068319-9ebf6726-bd4d-4564-a1a3-468d88872df3.png">

**Comment by rpgrca** [comment]
La pantalla de login no necesita ni nombre ni apellido, solamente el email y la contraseña, quitales eso y hacé la maquetación.
