### ISSUE TITLE
Ayer finalice de estudiar los apuntes de SGC. Avance con html. Pude generar enlaces en una prueba. Hoy continúe con dificultades en worpress. Cada vez que lo inicializo existen problemas con MySql. Pude resolverlo con mucho trabajo en eso. Mañana estudiare ingles principalmente y continuaré con html.

### ISSUE THREAD

**Issue by AhumadaCeleste** [rpgrca/proyecto-ispc-fullstack#17]
Ayer finalice de estudiar los apuntes de SGC. Avance con html. Pude generar enlaces en una prueba. Hoy continúe con dificultades en worpress. Cada vez que lo inicializo existen problemas con MySql. Pude resolverlo con mucho trabajo en eso. Mañana estudiare ingles principalmente y continuaré con html. 
No encuentro una buena definición de hipervínculos. Lo que encontré esta relacionado a documentos word y no se si, es un poco más amplio. Agradezco comentarios.

_Originally posted by @AhumadaCeleste in https://github.com/rpgrca/proyecto-ispc-fullstack/discussions/16#discussioncomment-3694629_

**Comment by rpgrca** [comment]
Transformaste tu comentario en una issue, como en realidad no es una issue te la cierro.

**Comment by AhumadaCeleste** [comment]
Hola Robert!!! Yes, asi lo hice para generar una interacción , porque
solicite help con un concepto.
Feliz día del estudiante y helada primavera.

Adiosss
