### ISSUE TITLE
#TK79 Agregar un usuario a la base de datos con los datos dados y tipo 2 (pujador) (INSERT)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#186]

**Comment by NataliaAlvarezIspc** [comment]
insert into Usuarios (nombre, apellido, email, usuario, clave, nacimiento, tipo_usuario)
values
('Rolando', 'Suarez', 'rolandosuarez@gmail.com', 'RolaSuarez', '123456', '1975-10-01', 2);

**Comment by rpgrca** [comment]
Está bien, solo que habría que usar los %s para parametrizar todo excepto el 2 del final.

**Comment by NataliaAlvarezIspc** [comment]
insert into Usuarios (nombre, apellido, email, usuario, clave, nacimiento, tipo_usuario)
values
('%s', '%s', '%s', '%s', '%s', '%s', 2);

**Comment by rpgrca** [comment]
No es necesario ponerle las comillas en los textos, lo hace MySQL solo cuando usás parametrizadas.

**Comment by NataliaAlvarezIspc** [comment]
oki

**Comment by NataliaAlvarezIspc** [comment]
quedo en commit de rama 191-agregar-registro-a-subasta
