### ISSUE TITLE
#TK84 Agregar un registro a la tabla de subasta con el título, descripción, imagen y fecha dados (INSERT)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#191]

**Comment by NataliaAlvarezIspc** [comment]
insert into Subastas (fecha, titulo, descripcion, imagen)
values
('2022-10-23', 'Escritorio estilo inglés', 'Escritorio estilo inglés con tapa de cuero en maderade roble
lavada. Con 5 cajones y silla haciendo juego. Tamaño: 1.10 metros de largo, 50 cm de profundidad y 80 cm de altura.',
'Escritorio estilo inglés');

**Comment by rpgrca** [comment]
Creo que éste está bien, solo con los %s en lugar de los valores para que sea parametrizable.

**Comment by NataliaAlvarezIspc** [comment]
insert into Subastas (fecha, titulo, descripcion, imagen)
values
('%s', '%s', '%s','%s');

**Comment by rpgrca** [comment]
Está bien pero no se usan las comillas, lo hace internamente MySQL cuando usás parametrizadas.
