### ISSUE TITLE
#TK90 Traer todas las ventas hechas para un comprador dado (SELECT, muy difícil!)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#197]

**Comment by NataliaAlvarezIspc** [comment]
creo que sería así:
select u.id, nombre, apellido, v.id, precio_final, id_puja, id_pujador
from Usuarios u
join Ventas v, Pujas
where u.id = id_pujador;

**Comment by rpgrca** [comment]
Creo que cuando usas join en lugar de where se usa on. No es necesario traer el nombre y el apellido o el id del usuario porque es uno de los datos que tenés así que no es necesario que se repita en cada registro del resultado. Y yo había pensado en traer únicamente las ventas en la última subasta pero creo que está bien traer todas juntas. También tenés que parametrizar el id, si funcionase eso traería todas las ventas a todos los usuarios cuando el usuario que está revisando su página de compras es uno solo.

**Comment by NataliaAlvarezIspc** [comment]
select v.id v_id, precio_final, comision, pago_consignatario
from Usuarios u
join Ventas v, Pujas
where u.id = id_pujador;

parametrizado seriía así?
select v.id v_id, precio_final, comision, pago_consignatario
from Usuarios u
join Ventas v, Pujas
%s where u.id = %s;

**Comment by NataliaAlvarezIspc** [comment]
El on no me lo toma, por eso le puse where,  supongo que porque tengo dos tablas en el join.

**Comment by NataliaAlvarezIspc** [comment]
está mal.. ahora lo corrijo

**Comment by rpgrca** [comment]
El where del final no va, el primer inner join hace lo que hace tu where, en el where iría u.id = %s. Personalmente no me gustan las abreviaturas pero funcionará.

**Comment by NataliaAlvarezIspc** [comment]
select v.id v_id, precio_final, comision, pago_consignatario
from Usuarios u
inner join Pujas p on u.id = p.id_pujador
inner join Ventas v on p.id = v.id_puja
where u.id = %s
