### ISSUE TITLE
#TK91 Traer la información de un usuario dado (SELECT)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#198]

**Comment by NataliaAlvarezIspc** [comment]
select * from Usuarios
where id = 1;

**Comment by rpgrca** [comment]
En lugar de poner un id poné %s que es el que usa Python para los queries parametrizados que luego se reemplaza con el id que quieras, para que quede un poco más claro.

https://pynative.com/python-mysql-execute-parameterized-query-using-prepared-statement/

**Comment by Brian-Almada** [comment]
queries parametrizados, si no entendí mal, es parecido a lo que hacen las Template Strings `$()` de JS ?  o las f-strings de Python cuando pones un print(f"bla bla {bla}") ??

**Comment by rpgrca** [comment]
Sí, es parecido a eso pero en SQL se usa %s (igual que en C).

**Comment by NataliaAlvarezIspc** [comment]
Sería asi?

select * from Usuarios
where id = %s;

No entiendo muy bien como sería porque no lo vimos... leí lo del  link pero no me queda muy claro como aplicarlo en el resto de los queries.

**Comment by NataliaAlvarezIspc** [comment]
select * from Usuarios
%s where id = %s;

**Comment by rpgrca** [comment]
El de arriba está bien, cada vez que tenés que poner un valor, por ejemplo que usaste 1 en el ID, poné %s. También cuando tenés que pasar un nombre, un título, etc.
