### ISSUE TITLE
#TK92 Sobreescribir la información de un usuario dado (UPDATE)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#199]

**Comment by claubott** [comment]
UPDATE Usuarios 
SET nombre = %s, apellido = %s, email = %s, usuario = %s, clave = %s, nacimiento = %s, tipo_usuario = %s  
WHERE id = %s;

**Comment by rpgrca** [comment]
El tipo de usuario no se puede sobreescribir.

**Comment by claubott** [comment]
Todo igual sin tipo_usuario:
UPDATE Usuarios 
SET nombre = %s, apellido = %s, email = %s, usuario = %s, clave = %s, nacimiento = %s 
WHERE id = %s;
