### ISSUE TITLE
#TK93 Crear caso de uso para CRUD

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#202]
Se pide crear casos de uso, como mínimo crud.

**Comment by rpgrca** [comment]
Supongo que sería algo así

![image](https://user-images.githubusercontent.com/15602473/197347698-b2442069-a873-4048-800b-c3b6718f8917.png)

**Comment by claubott** [comment]
CRUD tiene esa D de delete, pero no tenemos ninguna query para borrar. Podemos agregar algunas? 

Por ejemplo:
-- Borrar un artículo
DELETE FROM Articulos
WHERE id = %s;

**Comment by rpgrca** [comment]
Podemos agregar queries, sí, pero no tenemos forma de usarlos desde la página.

**Comment by rpgrca** [comment]
Esto es lo que se me ocurrió, tres casos de uso para crud en lugar de uno solo, caso de uso para la subasta por parte del martillero, y caso de uso para la subasta por parte del pujador.

![image](https://user-images.githubusercontent.com/15602473/200458271-c2bb552d-9e16-4d19-bb20-af33fb318c93.png)

**Comment by rpgrca** [comment]
Listo!
