### ISSUE TITLE
#TK07 Diseño en papel y lápiz o similar de pantalla de recuperación de datos

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#22]

**Comment by AhumadaCeleste** [comment]
![Uploading Recuperacion_contraseña.jpg…]()

**Comment by AhumadaCeleste** [comment]
![Recuperacion_contraseña](https://user-images.githubusercontent.com/106411071/192068453-7cab7363-ed07-478b-9b57-c5ae3e0f1832.jpg)

**Comment by rpgrca** [comment]
Me gusta, no estoy seguro de los colores y los botones redondos siempre son más complicados de codificar que los botones cuadrados pero me gusta.

**Comment by AhumadaCeleste** [comment]
Esta presentado solo en términos de estructura. 
Los colores comprendo que serían acordes a la estética del sitio.
Gracias por el dato la dificultad de la forma de los botones.

**Comment by AhumadaCeleste** [comment]
![ReestablecerContrsena](https://user-images.githubusercontent.com/106411071/194415188-1d4e528a-f803-4d54-843d-241b202eccfa.jpg)

**Comment by AhumadaCeleste** [comment]
Comparto nuevo archivo para continuar con la estética de los formularios de Brian
