### ISSUE TITLE
#TK13 Logo del sitio

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#25]
Necesitamos tener un logo que se utilizará en el encabezado de cada página y tal vez en el [favico](https://es.wikipedia.org/wiki/Favicon) del sitio.

**Comment by AhumadaCeleste** [comment]
Comparto imágenes por si son de utilidad
![logo](https://user-images.githubusercontent.com/106411071/192068730-901a461a-5c35-4e58-8553-398536b5f6ca.jpg)
![logo3](https://user-images.githubusercontent.com/106411071/192068743-642e3750-f9e2-4a5f-b688-6d74c1616260.png)
![BlackBidOn](https://user-images.githubusercontent.com/106411071/192068750-a42f41c6-1577-4f55-89a9-5406fea58256.jpg)

**Comment by rpgrca** [comment]
Reabriendo para que terminen de decidir

**Comment by Brian-Almada** [comment]
![bidon-logo](https://user-images.githubusercontent.com/100881466/192122533-43fcf07d-82f7-40e8-8e90-567311989d13.jpg)

**Comment by NataliaAlvarezIspc** [comment]
![logo_bidon](https://user-images.githubusercontent.com/106571110/194597681-b96ab2e0-798c-4182-b129-83b4298f48b1.svg)

**Comment by NataliaAlvarezIspc** [comment]
![bidon_logo](https://user-images.githubusercontent.com/106571110/194599700-190a0a27-95bc-4b20-9b93-b28ef8870eb9.svg)

**Comment by NataliaAlvarezIspc** [comment]
Subo archivo del logo en formato svg. Avisenme si lo pueden ver y si hay que hacerle modificaciones

**Comment by rpgrca** [comment]
Espectacular! Podés hacer uno con el martillo solo para usarlo de favico?

**Comment by NataliaAlvarezIspc** [comment]
Claro que si. En un rato lo subo.

**Comment by Brian-Almada** [comment]
Wow! quedó genial!!!!

**Comment by NataliaAlvarezIspc** [comment]
![martillo](https://user-images.githubusercontent.com/106571110/194727123-4084914c-1b61-4666-ba30-a16ed94a6b23.svg)

**Comment by Brian-Almada** [comment]
Je! va a estar muy bueno de favicon...
Incluso se puede usar hacer una animación en CSS y hacer que las letras en un momento se escondan detrás del martillo y luego de un rato salgan a su posición de nuevo. 
Ya estoy volando, pero quedaría bueno que no sea estático el logo.

**Comment by rpgrca** [comment]
Con esto ya estamos, cierro para que se pueda seguir con las demás tareas.
