### ISSUE TITLE
#TK10 Diseño de la pantalla de catálogo en lápiz y papel

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#27]

**Comment by IngridAlcocer05** [comment]
![catalogo](https://user-images.githubusercontent.com/106851962/194714462-cf9115da-6764-40db-85bc-a4f9c5b60744.png)

**Comment by rpgrca** [comment]
La idea está bien, creo que la barra superior no sería necesaria porque nuestro sistema solo sirve para un martillero y ese martillero solo puede hacer una subasta así que sería mostrar el catálogo con la imagen, el título y la descripción del lote, el valor de arranque y creo que nada más porque la fecha va a ser casi siempre la misma (si fuese en otra fecha armaría otra subasta).

La hora depende bastante de qué tan rápido se venden, por lo general entre que se muestra, se abre, se muestra y se explica durante 30 segundos y después la puja termina en unos 3 minutos (a 20 lotes por hora), sin embargo si los pujadores son lentos puede desfazarse bastante y en ese caso los horarios quedarían todos mal.

**Comment by IngridAlcocer05** [comment]
Adjunto nuevo boceto con los cambios necesarios
![catalogo-lote](https://user-images.githubusercontent.com/106851962/194730117-12016f04-94d7-49c8-9e95-de73924c9365.png)

**Comment by rpgrca** [comment]
Está bien! Fijate que la pantalla de consignaciones y la de compras también son listas de lotes así que podés basarte en ellas o copiarlas cambiándole el título de la página.
