### ISSUE TITLE
Completar ERS

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#3]
Ayudar a completar la [especificación de requisitos](https://github.com/rpgrca/proyecto-ispc-fullstack/wiki/Especificaci%C3%B3n-de-requisitos-de-software) de software del proyecto

**Comment by NataliaAlvarezIspc** [comment]
Me ocupo de hacer la sección RESUMEN

**Comment by rpgrca** [comment]
Terminado! Pero me olvidé de cerrarlo en el sprint 0.
