### ISSUE TITLE
Diseñar logo Empresa Almoneda

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#33]
### Discussed in https://github.com/rpgrca/proyecto-ispc-fullstack/discussions/15

<div type='discussions-op-text'>

<sup>Originally posted by **rpgrca** September 19, 2022</sup>
Deberíamos darle un nombre al proyecto? Así como existe "MediaWiki", como existe "Wordpress", etc, se le ocurre algún nombre para darle al sistema y usarlo por ejemplo en el documento de especificaciones, en el copyright, etc?</div>

### **Almoneda**

**Comment by rpgrca** [comment]
Viendo como almoneda (como la muchas o la mayoría de las palabras que empiezan con al) es de origen turco tal vez podríamos combinar un gráfico de una moneda con algo que represente a Turquía o los árabes. Un camello? Una ciudad antigua de piedra? Alguna palabra en turco?

**Comment by Brian-Almada** [comment]
Les comparto una idea que tuve (si aún vale la discusión)..
Se me ocurrió un texto elegante y alargado con lo refinado del color simil dorado y con un fondo con 3 anillos que representan al que quiere vender un producto, el del medio el martillero y el último el que puja y quiere adquirir el producto. Estos anillos a su vez tienen más anillos superpuestos para darle movimiento que representas muchas transacciones, al igual que el anillo del medio tiene unas flechas que van y vienen para el mismo objetivo. Les comparto para ver si les gusta o se inspirar a mejorarlo.

![logo-almoneda](https://user-images.githubusercontent.com/100881466/193691835-bbef8d7b-98be-4789-b89b-59c892f1f93e.png)

**Comment by NataliaAlvarezIspc** [comment]
Me gusta la idea, solo que le pondría "soluciones web" o algo así abajo.

**Comment by Brian-Almada** [comment]
El subtitulo lo dejé pero me arrepentí un poco después cuando lo vi.
"Soluciones web" pienso que nos llevaría a ser una empresa más abarcadora, no?
Pensé en "software para subastas" pensando en que nos vamos a dedicar a ese tipo de negocios nomás. Aun así, creo que visualmente me está molestando el subtitulo (quizás se pueda corregir la posición, más abajo tal vez ?)

**Comment by rpgrca** [comment]
Me gusta el logo! Coincido con que software para subastas te encasilla, pero soluciones web también porque ya estás rechazando cualquier proyecto desktop o incluso mobile. Yo le pondría soluciones tecnológicas para dejar abierta la puerta a cualquier tipo de software (e incluso hardware). Pero el logo me gusta, armá uno en SVG o png transparente para usarlo en el sitio.

**Comment by rpgrca** [comment]
Oops, botón equivocado.

**Comment by NataliaAlvarezIspc** [comment]
Si queres Brian, mandame el fondo de los circulos por separado y el tipo de fuente que usaste y lo paso a formato svg y le agrego soluciones técnologicas

**Comment by Brian-Almada** [comment]
![circulogo](https://user-images.githubusercontent.com/100881466/194728086-2247a316-7e11-4802-87fb-446ba137eb05.png)

El tipo de fuente que usé para ALMONEDA es "Trajan PRO"
Y el subtítulo es "Sansation"

**Comment by rpgrca** [comment]
Estaría bueno que no tenga el Activar Windows ahí :D

**Comment by Brian-Almada** [comment]
Corregido :)

**Comment by rpgrca** [comment]
@NataliaAlvarezIspc lo está haciendo en SVG creo? En cuanto lo suba puede cerrar esta tarea.

**Comment by NataliaAlvarezIspc** [comment]
![almoneda_circulos](https://user-images.githubusercontent.com/106571110/194734878-f19f9e8b-7f9d-4e0d-ada0-33e46cdb821b.svg)

**Comment by NataliaAlvarezIspc** [comment]
![almoneda](https://user-images.githubusercontent.com/106571110/194734961-5a5385f5-0838-4a75-a090-0944ce9fd0b5.svg)

**Comment by NataliaAlvarezIspc** [comment]
mañana lo termino y lo mando.. hay que dibujarlo de nuevo.

**Comment by claubott** [comment]
Subo logo y dos versiones de favicon en formato png
![almoneda_logo](https://user-images.githubusercontent.com/37263110/197605376-816f38c8-f0de-4ccf-a19d-6c1ae41a2af4.png)
![almoneda_favicon1](https://user-images.githubusercontent.com/37263110/197605381-87343e50-cbff-4cd4-82d4-5c14408b12b9.png)
![almoneda_favicon2](https://user-images.githubusercontent.com/37263110/197605368-bb804e9d-93d1-42c8-839b-76b15ab1120e.png)

**Comment by NataliaAlvarezIspc** [comment]
Buenísimo Clau! 
Si puedo opinar me gusta más el 2do. favicon

**Comment by rpgrca** [comment]
También me gusta más la segunda versión, sí!

**Comment by Brian-Almada** [comment]
Idem!! voto por el 2
