### ISSUE TITLE
#US06: Usuario Martillero

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#34]
### Descripción

Como usuario Martillero quiero poder acceder como administrador para editar los contenidos de la página principal

### Tareas

- [x] #108

**Comment by rpgrca** [comment]
La refiné un poco poniendo "editar los contenidos", si no se vuelve una tarea muy grande (editar los pujadores, editar los contenidos, editar los lotes, editar los consignatarios, etc).

**Comment by NataliaAlvarezIspc** [comment]
Perfecto!

**Comment by AhumadaCeleste** [comment]
No logro cambiarle el nombre a la issue para que quede como la "user history". **"Administrador para editar los contenidos de la página principal"** Quedo a la espera de de definir que sobra o faltaría.
![Admin Edicion](https://user-images.githubusercontent.com/106411071/194782887-79e0f0d5-bd36-4c1c-add8-31b33cc1aaa3.png)

**Comment by rpgrca** [comment]
Listo!
