### ISSUE TITLE
#TK13 Diseño en papel y lápiz o similar del formulario de contacto

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#41]

**Comment by claubott** [comment]
Boceto de la página de contacto para usuarios no logueados:

![Image](https://user-images.githubusercontent.com/37263110/194688862-bf6e705d-aa07-4a23-ae34-e28fa22ffbf0.jpg)

**Comment by rpgrca** [comment]
Lo de la ubicación me parece algo innecesario porque no es necesario que le digas dónde estás para contactarte. Quitando eso y centrando el Contacto me parece perfecto.

**Comment by claubott** [comment]
Hola Roberto! Yo prefiero dejar el mapa. Me da oportunidad de trabajar en el diseño responsive de la página. Y además en algún momento vamos a tener que consumir una api y ahí se va a poder integrar con google maps. Mientras solo va a ser una imagen con un link a google maps. Tengo una idea de diseño, pero la pongo en la tarea de css para no mezclar las cosas.

**Comment by rpgrca** [comment]
Lo discutimos en la weekly de mañana.
