### ISSUE TITLE
#TK15 Estilo para el formulario de contacto con CSS

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#43]

**Comment by claubott** [comment]
Tengo este estilo y copy pensado para la página de contacto anónima:


![Image](https://user-images.githubusercontent.com/37263110/194734618-7da58cf5-7732-48dd-8ffa-a578116412b8.jpg)


También tengo esta alternativa de menú oscuro:


![Image](https://user-images.githubusercontent.com/37263110/194734622-e2fb63d3-4c66-44ba-9b78-578dd05a2f48.jpg)


El logo lo hice en illustrator. Fue antes que Natalia actualizara su tarea. Era solo para mí, para tener algo que poner en mi diseño, pero bien se podría considerar como alternativa.
