### ISSUE TITLE
#TK16 Diseño en papel y lápiz o similar del formulario de contacto

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#47]
El formulario de contacto de miembros no necesita ni el nombre ni el mail ya que usaría los que están registrados por el usuario.

**Comment by Brian-Almada** [comment]
![diseñohtml-contactmiembro](https://user-images.githubusercontent.com/100881466/193709761-44bd9500-33a9-485f-872e-90777bfc02e7.png)
Bosquejo que se encuentra en Discussions. 
Este tiene una última modificación.

**Comment by rpgrca** [comment]
Te falta el botón para enviar pero la idea general está bien.
