### ISSUE TITLE
#US01: Pantalla de registración

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#5]
### Descripción

Como usuario nuevo cuando quiero usar el sitio entonces tengo que registrarme.

### Tareas

- [x] #7
- [x] #8
- [x] #9

**Comment by AhumadaCeleste** [comment]
![Image](https://user-images.githubusercontent.com/106411071/194781365-c5922e42-4c6b-477a-bc94-8827c9737931.jpg)

**Comment by rpgrca** [comment]
Listo!
