### ISSUE TITLE
#TK19 Diseño en papel y lápiz o similar de página de perfil

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#51]

**Comment by rocappellano** [comment]
![1665196053049601455047472098513](https://user-images.githubusercontent.com/107150337/194683466-d64ca4cd-8db5-47cd-b761-27f95dc954cd.jpg)

**Comment by rocappellano** [comment]
![Uploading 1665196089391351520117337279607.jpg…]()

**Comment by rpgrca** [comment]
La parte de contraseña debería estar abajo: contraseña anterior, nueva contraseña, repetir nueva contraseña, tres textboxes para confirmar que el que quiere cambiar la clave es el dueño de la cuenta y para confirmar la clave también.

**Comment by rpgrca** [comment]
Tené en cuenta eso para empezar con la maquetación.
