### ISSUE TITLE
 Diseñar una pantalla de registración

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#6]
(Viene de #5) Diseñar una pantalla de registración (en papel y lápiz, Paint, etc). La pantalla de registración debe tener un textbox para colocar el e-mail y otro para el password además de un botón para ejecutar la registración.

**Comment by rpgrca** [comment]
Duplicada de #7

**Comment by AhumadaCeleste** [comment]
![Image](https://user-images.githubusercontent.com/106411071/194782305-eefab3f9-e737-428d-9fc6-43769230c8e6.jpg)
