### ISSUE TITLE
#TK23 Diseñar en lápiz y papel página de lotes propios

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#62]

**Comment by AhumadaCeleste** [comment]
![Tk23Pag lotes propios](https://user-images.githubusercontent.com/106411071/194561254-1ab2a1b0-6d6a-4bd5-bcba-a2f84f79f220.png)

**Comment by rpgrca** [comment]
La página de lotes va a ser similar a la página de compras, en principio la página de compras es vertical pero podemos hacer algo horizontal para celulares. Está bien el planteo.
