### ISSUE TITLE
#TK25 Dibujar en lápiz y papel menú de navegacion

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#66]

**Comment by rocappellano** [comment]
![Uploading 16654351551921473764985563093450.jpg…]()

**Comment by rocappellano** [comment]
![Uploading IMG_20221010_175342.jpg…]()

**Comment by rocappellano** [comment]
![16654353735882440629158080279630](https://user-images.githubusercontent.com/107150337/194951060-6cfa7c61-4b3a-40d7-b62f-984b75681455.jpg)

**Comment by rpgrca** [comment]
También podría tener la de contactos, y en el caso de estar logueado como pujador tendría una lista de compras y en caso de estar como consignatario una lista de lotes. La de lotes se llamaría "catálogo" para no confundir con los lotes de comprados y vendidos. Pero más o menos la idea está bien.
