### ISSUE TITLE
#TK01 Diseñar una pantalla de registración (en papel y lápiz, Paint, etc)

### ISSUE THREAD

**Issue by rpgrca** [rpgrca/proyecto-ispc-fullstack#7]
Diseñar una pantalla de registración (en papel y lápiz, Paint, etc). La pantalla de registración debe tener un textbox para colocar el e-mail y otro para el password además de un botón para ejecutar la registración.

**Comment by AhumadaCeleste** [comment]
[PantallaDeRegistracion.pdf](https://github.com/rpgrca/proyecto-ispc-fullstack/files/9718875/PantallaDeRegistracion.pdf)

**Comment by AhumadaCeleste** [comment]
Subo nuevo archivo respetando los concepto y colores presentados por Brian para comenzar a establecer estética acorde al logo.

**Comment by NataliaAlvarezIspc** [comment]
No se puede ver el archivo. Mandalo en  jpg

**Comment by AhumadaCeleste** [comment]
Perdón. Equivoque el botón y cerré. Abro nuevamente. Disculpas

**Comment by NataliaAlvarezIspc** [comment]
Sigo sin poder ver el archivo. No se si estoy haciendo algo mal.

**Comment by AhumadaCeleste** [comment]
![PantallaDeRegistracion](https://user-images.githubusercontent.com/106411071/194781323-6b7e3063-4cd4-4ac0-a88b-757fd65b618a.jpg)

**Comment by rpgrca** [comment]
Le quitaría el imperativo a "regístrate", password tiene dos s y tendría que tener también nombre de usuario con el que quiere ser conocido en el sitio en base a lo que hablamos en la parte de análisis. También tendría que tener un link tipo "si ya tiene cuenta puede ingresar aquí" para ir a la pantalla de login, y "Si olvidó su cuenta puede hacer click aquí" para recuperar la clave, pero la idea está bien.
