### ISSUE TITLE
#TK28 Dibujar en lapiz y papel pagina de compras realizadas.

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#70]

**Comment by rpgrca** [comment]
![image](https://user-images.githubusercontent.com/15602473/194052750-1e4f24e0-6bcf-40cb-82af-8de5feae155c.png)

El encabezado va a ser fijo y otra tarea, el contenido de la página de compras realizadas va a ser un listado con la imagen, el número de lote, la descripción del lote, el precio al que salió publicado y el precio final.
