### ISSUE TITLE
#US13 Pagina de creacion de Lotes

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#77]
### Descripción

Como martillero cuando quiero agregar un lote para subastar entonces tengo que ir a la página de creación de lotes.

### Tareas

- [x] #78
- [x] #79
- [x] #80

**Comment by AhumadaCeleste** [comment]
La idea sugerida es que desde una sola pantalla se pueda crear un lote para darlo de alta, consultarlo y modificar el estado del mismo. Quedo atenta a sugerencias de cambios.

**Comment by rpgrca** [comment]
Me pareció muy buena, el problema es que cuando vas a dar de alta un lote lo que te pide debe ser lo mínimo indispensable, todavía no sabe en qué subasta va a ser vendido ni quién es el que ganó la subasta. Por eso la parte del centro para la izquierda es la que podríamos usar, el evento es para la creación de subasta, el pujador beneficiado es para el la venta en sí.

**Comment by AhumadaCeleste** [comment]
![Image](https://user-images.githubusercontent.com/106411071/194782006-2eb3b097-3a56-4e31-abe0-49f41d0b3fa9.png)

**Comment by rpgrca** [comment]
Listo!
