### ISSUE TITLE
#TK34 Diseño en lapiz y papel de pagina de creacion de lotes.

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#78]

**Comment by AhumadaCeleste** [comment]
![creacion cambio estado lote](https://user-images.githubusercontent.com/106411071/194560099-5e81792f-c4b8-41eb-a29d-ef223fb8a64e.png)

**Comment by rpgrca** [comment]
Buenísimo! La parte de la izquierda y centro está bien, la de la derecha no es exactamente de la creación del lote en sí sino de una venta. Me quedo con el centro para la izquierda.
