### ISSUE TITLE
#US14 Crear página para crear subasta

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#81]
### Descripción

Como martillero cuando quiero crear una subasta entonces tengo que ir a la página de subastas.

### Tareas

- [x] #82
- [x] #83
- [x] #84

**Comment by rpgrca** [comment]
Con el diseño me dí cuenta que tomaron la #US14 y la #US15 como iguales así que lo cambio, la #US14 es para armar la subasta (elegir los lotes que van a entrar en la subasta, ordenarlos, etc) y la #US15 es la subasta en sí.

**Comment by AhumadaCeleste** [comment]
![Image](https://user-images.githubusercontent.com/106411071/194844140-cc8a717e-b9bd-4a45-9a3f-94ce83077a7a.png)

**Comment by rpgrca** [comment]
Listo!
