### ISSUE TITLE
#TK37 Dibujar en papel y lapiz pagina para crear las subastas

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#82]

**Comment by AhumadaCeleste** [comment]
![TK40pag para subastar](https://user-images.githubusercontent.com/106411071/194560873-afff389b-fe45-432b-8ee1-22dfb0c6fd1d.png)

**Comment by rpgrca** [comment]
Perfecto! Por ahí hacemos unos retoques pero así está bien para que tengan una idea de cómo sería.

**Comment by rpgrca** [comment]
Me di cuenta que tomaron la #US14 y la #US15 como la misma tarea así que la estoy cambiando, la #US14 es la parte de creación de la subasta, elegir los lotes, ordenarlos y publicitarlo eventualmente en la página principal y la #US15 es la subasta en sí, así que este diseño está bien para la #US15 pero para esta va a ser diferente.

**Comment by rpgrca** [comment]
Listo!
