### ISSUE TITLE
#TK38 Maquetar en HTML pagina para crear subastas

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#83]

**Comment by AhumadaCeleste** [comment]
Me parece que se repite la issue en el tk41. Cerramos y cargo en el 41?

**Comment by rpgrca** [comment]
Estaba mal el título, esta tarea es para crear subastas, elegir los lotes que se van a subastar y ordenarlos.

**Comment by AhumadaCeleste** [comment]
En ese caso esta recién subido el archivo con la correcciones.

**Comment by AhumadaCeleste** [comment]
https://github.com/rpgrca/proyecto-ispc-fullstack/issues/82
resuelto alli.

**Comment by rpgrca** [comment]
Listo!
