### ISSUE TITLE
#US15 Crear pagina para subastar lotes (martillero)

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#85]
### Descripción

Como martillero cuando quiero subastar un lote entonces tengo que ir a la página de subastas y subastar el lote.

### Tareas

- [x] #86
- [x] #87
- [x] #88

**Comment by AhumadaCeleste** [comment]
![TK40pag para subastar](https://user-images.githubusercontent.com/106411071/194559929-54c435ef-13b1-412e-b9a5-0a83f4e201ea.png)

**Comment by rpgrca** [comment]
Está listo!
