### ISSUE TITLE
#TK40 Diseñar en lapiz y papel pagina para subastar lotes (martillero)

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [rpgrca/proyecto-ispc-fullstack#86]

**Comment by AhumadaCeleste** [comment]
![TK40pag para subastar](https://user-images.githubusercontent.com/106411071/194544589-f18ed90d-d81d-4098-b640-5bec33aa8487.png)

**Comment by AhumadaCeleste** [comment]
Estoy atenta a sugerencias por modificaciones.

**Comment by rpgrca** [comment]
Digamos que la selección de la oferta ganadora es automática. El botón de finalizar evento sería "cerrar puja" que sería equivalente al tercer golpe del martillo y automáticamente la oferta más alta gana. Y publicar lote sería siguiente lote (ya que los lotes ya están armados en el catálogo). Pero el resto está bien.
